[package]
name = "cml-chain-json-schema-gen"
version = "6.2.0"
edition = "2024"
keywords = ["cardano"]

[package.metadata.cddl-codegen]
generated-with = "0.1.0"

[dependencies]
cml-core = { path = "../../../core/rust" }
serde_json = "1.0.57"
schemars = "1.2.1"
cml-chain = { path = "../../rust" }
cml-crypto = { path = "../../../crypto/rust" }
