//! Generated by cddl-codegen. This crate is tool-owned and is DELETED AND REWRITTEN on every
//! regeneration — do not edit it.
//!
//! It depends on the generated crate with `default-features = false`, so a green check here means
//! that crate builds with no `std`. Host targets always link `std`, so the check needs a no-std
//! target:
//!
//!   cargo check --manifest-path <output-root>/no-std-check/Cargo.toml --target thumbv7m-none-eabi
//!
//! A failure here with an otherwise unmodified generated crate is caused by hand-written additions —
//! which, in a split layout, includes the hand-owned half of a runtime crate this one depends on: its
//! crate root, and any dependency it adds. The tool-written half forwards: every dependency this crate
//! takes with `default-features = false` is named by its own `std` feature, so turning `std` off here
//! turns it off all the way down.
//!
//! One caveat when reading a RED check: cargo stops at the first crate that fails, so everything after
//! it — the crate under test included — is never compiled at all. A failure in a dependency is a
//! verdict about that dependency and clears nothing behind it. A crate was actually reached only if a
//! `Checking <name>` line for it appears in the output; the rest becomes visible once the first
//! failure is fixed.

#![no_std]

// This crate was generated with `--common-import-override`, so it owns no runtime modules to name a
// type from; depending on it is what forces its whole `no_std` build. NOTE: the override crate must
// be in this crate's `[dependencies]` for the check to run at all — `--rust-dep` (or a `deps` edge
// under `--config`) writes that entry, and a hand-added one does just as well.
use cml_cip25 as _;
