block =
  [ header
  , transaction_bodies         : [* transaction_body]
  , transaction_witness_sets   : [* transaction_witness_set]
  , auxiliary_data_set         : {* transaction_index => auxiliary_data }
  , invalid_transactions       : [* transaction_index ]
  ]; Valid blocks must also satisfy the following two constraints:
   ; 1) the length of transaction_bodies and transaction_witness_sets
   ;    must be the same
   ; 2) every transaction_index must be strictly smaller than the
   ;    length of transaction_bodies

header =
  [ header_body
  , body_signature : KES_signature
  ]

header_body =
  [ block_number     : uint
  , slot             : uint
  , prev_hash        : block_header_hash / null
  , issuer_vkey      : $vkey
  , vrf_vkey         : $VRF_vkey
  , vrf_result       : $VRF_cert ; New, replaces nonce_vrf and leader_vrf
  , block_body_size  : uint
  , block_body_hash  : block_body_hash ; merkle triple root
  , operational_cert
  , protocol_version
  ]

operational_cert =
  ( hot_vkey        : $KES_vkey
  , sequence_number : uint
  , kes_period      : uint
  , sigma           : ed25519_signature
  )

protocol_version = (major: uint, minor: uint)
