certificate =
  [ stake_registration
  // stake_deregistration
  // stake_delegation
  // pool_registration
  // pool_retirement
  // genesis_key_delegation
  // move_instantaneous_rewards_cert
  ]

stake_registration = (tag: 0, stake_credential)
stake_deregistration = (tag: 1, stake_credential)
stake_delegation = (tag: 2, stake_credential, ed25519_key_hash)
pool_registration = (tag: 3, pool_params)
pool_retirement = (tag: 4, ed25519_key_hash, epoch)
genesis_key_delegation = (tag: 5, genesis_hash, genesis_delegate_hash, VRF_key_hash)
move_instantaneous_rewards_cert = (tag: 6, move_instantaneous_reward)

MIR_pot = 0 ; @name reserve
        / 1 ; @name treasury

MIR_action = { * stake_credential => delta_coin } ; @name to_stake_credentials
           / coin                                 ; @name to_other_pot

move_instantaneous_reward = [
  pot: MIR_pot,
  action: MIR_action,
]

; The first field determines where the funds are drawn from.
; 0 denotes the reserves, 1 denotes the treasury.
; If the second field is a map, funds are moved to stake credentials,
; otherwise the funds are given to the other accounting pot.

pool_params = ( operator:       ed25519_key_hash
              , vrf_keyhash:    VRF_key_hash
              , pledge:         coin
              , cost:           coin
              , margin:         unit_interval
              , reward_account: reward_account
              , pool_owners:    [* ed25519_key_hash]
              , relays:         [* relay]
              , pool_metadata:  pool_metadata / null
              )

ipv4 = bytes .size 4
ipv6 = bytes .size 16
dns_name = tstr .size (0..64)

single_host_addr = ( tag: 0
                   , port / null
                   , ipv4 / null
                   , ipv6 / null
                   )
single_host_name = ( tag: 1
                   , port / null
                   , dns_name ; An A or AAAA DNS record
                   )
multi_host_name = ( tag: 2
                   , dns_name ; A SRV DNS record
                   )
relay =
  [  single_host_addr
  // single_host_name
  // multi_host_name
  ]

pool_metadata = [url, pool_metadata_hash]
url = tstr .size (0..64)


stake_credential = [
  ; @name PubKey
  tag: 0, hash: ed25519_key_hash //
  ; @name Script
  tag: 1, hash: script_hash
  ]
