$hash28 /= bytes .size 28
$hash32 /= bytes .size 32

$vkey /= bytes .size 8

$vrf_vkey /= bytes .size 8
$vrf_cert /= [bytes, bytes .size 10]
natural = #6.2(bytes)

$kes_vkey /= bytes .size 8
$kes_signature /= bytes .size 32
signkeyKES = bytes .size 16

$signature /= bytes .size 16

$nonce /= [ 0 // 1, bytes .size 32 ]

addr_keyhash          = $hash28
genesis_delegate_hash = $hash28
pool_keyhash          = $hash28
genesishash           = $hash28

vrf_keyhash           = $hash32
auxiliary_data_hash   = $hash32
pool_metadata_hash    = $hash32

; To compute a script hash, note that you must prepend
; a tag to the bytes of the script before hashing.
; The tag is determined by the language.
; The tags in the Babbage era are:
;   "\x00" for multisig scripts
;   "\x01" for Plutus V1 scripts
;   "\x02" for Plutus V2 scripts
scripthash            = $hash28

datum_hash = $hash32
