value = _CDDL_CODEGEN_EXTERN_TYPE_
asset_name = _CDDL_CODEGEN_EXTERN_TYPE_

non_zero_int_64 = -9223372036854775808 .. 9223372036854775807 ; @rust_name NonZeroInt64
mint = { * policy_id => { * asset_name => non_zero_int_64 } } ; @rust_name Mint
coin = uint