vkeywitness = _CDDL_CODEGEN_EXTERN_TYPE_
bootstrap_witness = _CDDL_CODEGEN_EXTERN_TYPE_
nonce = _CDDL_CODEGEN_EXTERN_TYPE_
KES_signature = _CDDL_CODEGEN_EXTERN_TYPE_
VRF_cert = _CDDL_CODEGEN_EXTERN_TYPE_

vkey = _CDDL_CODEGEN_RAW_BYTES_TYPE_
VRF_vkey = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
KES_vkey = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
ed25519_signature = _CDDL_CODEGEN_RAW_BYTES_TYPE_
ed25519_key_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
genesis_delegate_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
genesis_hash           = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
VRF_key_hash           = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
auxiliary_data_hash   = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
pool_metadata_hash    = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
script_hash            = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
datum_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
block_body_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
block_header_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
transaction_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy
script_data_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @copy