transaction_input = _CDDL_CODEGEN_EXTERN_TYPE_
transaction_body = _CDDL_CODEGEN_EXTERN_TYPE_
native_script = _CDDL_CODEGEN_EXTERN_TYPE_
alonzo_format_tx_out = _CDDL_CODEGEN_EXTERN_TYPE_
datum_option = _CDDL_CODEGEN_EXTERN_TYPE_