; _CDDL_CODEGEN_EXTERN_INTERFACE_ v1
; unexported: CIP36_legacy_key_registration — references excluded public_key
; unexported: CIP36_stake_credential — references excluded public_key
; unexported: CIP36_stake_witness — references excluded ed25519_signature
; unexported: CIP36_staking_pub_key — references excluded public_key
; unexported: CIP36_voting_pub_key — references excluded public_key
CIP36_delegation = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name CIP36Delegation
CIP36_delegation_distribution = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name CIP36DelegationDistribution
CIP36_deregistration_cbor = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name CIP36DeregistrationCbor
CIP36_deregistration_witness = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name CIP36DeregistrationWitness
CIP36_key_deregistration = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name CIP36KeyDeregistration
CIP36_key_registration = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name CIP36KeyRegistration
CIP36_nonce = uint ; @rust_name CIP36Nonce
CIP36_registration_cbor = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name CIP36RegistrationCbor
CIP36_registration_witness = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name CIP36RegistrationWitness
CIP36_voting_purpose = uint ; @rust_name CIP36VotingPurpose
CIP36_weight = uint .size 4 ; @rust_name CIP36Weight
