[package]
name = "cml-cip36"
version = "6.0.1"
edition = "2018"
authors = ["dcSpark"]
license = "MIT"
description = "Multiplatform SDK for CIP36 Catalyst voting functionality"
documentation = "https://github.com/dcSpark/cardano-multiplatform-lib/docs"
repository = "https://github.com/dcSpark/cardano-multiplatform-lib"
readme = "../../README.md"
keywords = ["cardano", "cip36"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cml-core = { "path" = "../../core/rust", version = "6.0.1" }
cml-crypto = { "path" = "../../crypto/rust", version = "6.0.1" }
cml-chain = { "path" = "../../chain/rust", version = "6.0.1" }
cbor_event.workspace = true
linked-hash-map.workspace = true
derivative.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
hex.workspace = true
thiserror.workspace = true