[package]
name = "cml-cip36-wasm"
version = "6.0.1"
edition = "2018"
authors = ["dcSpark"]
license = "MIT"
description = "Multiplatform WASM SDK for CIP36 Catalyst voting functionality"
documentation = "https://github.com/dcSpark/cardano-multiplatform-lib/docs"
repository = "https://github.com/dcSpark/cardano-multiplatform-lib"
readme = "../../README.md"
keywords = ["cardano", "cip36"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cml-cip36 = { path = "../rust", version = "6.0.1" }
cml-crypto = { path = "../../crypto/rust", version = "6.0.1" }
cml-crypto-wasm = { path = "../../crypto/wasm", version = "6.0.1" }
cml-chain = { path = "../../chain/rust", version = "6.0.1" }
cml-chain-wasm = { path = "../../chain/wasm", version = "6.0.1" }
cml-core = { path = "../../core/rust", version = "6.0.1" }
cml-core-wasm = { path = "../../core/wasm", version = "6.0.1" }
cbor_event.workspace = true
hex.workspace = true
wasm-bindgen.workspace = true
linked-hash-map.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
