; _CDDL_CODEGEN_EXTERN_INTERFACE_ v1
alonzo_format_tx_out = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name AlonzoFormatTxOut
conway_format_tx_out = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name ConwayFormatTxOut
datum_option = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name DatumOption
native_script = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name NativeScript
required_signers = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name RequiredSigners
script_all = (tag: 1, native_scripts: [* native_script]) ; @rust_name ScriptAll
script_any = (tag: 2, native_scripts: [* native_script]) ; @rust_name ScriptAny
script_invalid_before = (tag: 4, before: slot) ; @rust_name ScriptInvalidBefore
script_invalid_hereafter = (tag: 5, after: slot) ; @rust_name ScriptInvalidHereafter
script_n_of_k = (tag: 3, n: uint, native_scripts: [* native_script]) ; @rust_name ScriptNOfK
script_pubkey = (tag: 0, ed25519_key_hash: ed25519_key_hash) ; @rust_name ScriptPubkey
script_ref = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name ScriptRef
transaction = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name Transaction
transaction_body = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name TransactionBody
transaction_input = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name TransactionInput
transaction_output = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name TransactionOutput
transaction_witness_set = _CDDL_CODEGEN_EXTERN_TYPE_ ; @rust_name TransactionWitnessSet
