[package]
name = "cardano-multiplatform-lib"
version = "6.0.1"
edition = "2018"
keywords = ["cardano"]
license = "MIT"
description = "Multiplatform WASM SDK containing the most common CML crates for Cardano blockchain functionality"
documentation = "https://github.com/dcSpark/cardano-multiplatform-lib/docs"
repository = "https://github.com/dcSpark/cardano-multiplatform-lib"
readme = "../../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cml-chain-wasm = { path = "../../chain/wasm", version = "6.0.1" }
cml-cip25-wasm = { path = "../../cip25/wasm", version = "6.0.1" }
cml-cip36-wasm = { path = "../../cip36/wasm", version = "6.0.1" }
cml-crypto-wasm = { path = "../../crypto/wasm", version = "6.0.1" }
cml-core-wasm = { path = "../../core/wasm", version = "6.0.1" }
cbor_event.workspace = true
hex.workspace = true
linked-hash-map.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
