; this is done in cml-core:

; transaction_metadatum =
;    { * transaction_metadatum => transaction_metadatum } ; @name map
;  / [ * transaction_metadatum ] ; @name list
;  / int
;  / bytes .size (0..64)
;  / text .size (0..64)

; metadata = { * transaction_metadatum_label => transaction_metadatum }
; the above is correct but we needed to hand-write it to allow for duplicate keys
metadata = _CDDL_CODEGEN_EXTERN_TYPE_

shelley_format_aux_data = metadata
shelley_MA_format_aux_data = [ transaction_metadata: metadata ; Shelley-ma
    , auxiliary_scripts: [ * native_script ]
    ]

conway_format_aux_data = #6.259({
  ? 0 => metadata,               ; @name metadata        
  ? 1 => [ * native_script ],    ; @name native_scripts
  ? 2 => [ * plutus_v1_script ], ; @name plutus_v1_scripts
  ? 3 => [ * plutus_v2_script ], ; @name plutus_v2_scripts
  ? 4 => [ * plutus_v3_script ], ; @name plutus_v3_scripts
})

auxiliary_data =
  shelley_format_aux_data ; @name shelley
  / shelley_MA_format_aux_data ; @name shelley_MA
  / conway_format_aux_data ; @name conway
