[package]
name = "cml-crypto-wasm"
version = "6.0.1"
edition = "2018"
authors = ["dcSpark"]
license = "MIT"
description = "Multiplatform WASM SDK for Cardano-related cryptographic functionality"
documentation = "https://github.com/dcSpark/cardano-multiplatform-lib/docs"
repository = "https://github.com/dcSpark/cardano-multiplatform-lib"
readme = "../../README.md"
keywords = ["cardano"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cml-core-wasm = { path = "../../core/wasm", version = "6.0.1" }
cml-crypto = { path = "../rust", version = "6.0.1" }
cbor_event.workspace = true
wasm-bindgen.workspace = true
linked-hash-map.workspace = true
serde_json.workspace = true
