; babbage block
block = _CDDL_CODEGEN_EXTERN_TYPE_

byron_block = _CDDL_CODEGEN_EXTERN_TYPE_

multi_era_block =
    byron_block   ; @name byron
  / shelley_block ; @name Shelley
  / allegra_block ; @name Allegra
  / mary_block    ; @name Mary
  / alonzo_block  ; @name Alonzo
  / babbage_block ; @name Babbage
  / block         ; @name Conway

multi_era_transaction_body =
    byron_tx                 ; @name byron
  / shelley_transaction_body ; @name Shelley
  / allegra_transaction_body ; @name Allegra
  / mary_transaction_body    ; @name Mary
  / alonzo_transaction_body  ; @name Alonzo
  / babbage_transaction_body ; @name Babbage
  / transaction_body         ; @name Conway
