; babbage block
block = _CDDL_CODEGEN_EXTERN_TYPE_

mutli_era_block =
    shelley_block ; @name Shelley
  / allegra_block ; @name Allegra
  / mary_block    ; @name Mary
  / alonzo_block  ; @name Alonzo
  / block         ; @name Babbage