string64 = text .size (0..64)

; actually also has to be a hex string
policy_id_v1 = text .size 56 ; @newtype
; utf8 text
asset_name_v1 = string64 ; @newtype

; no longer in text
policy_id_v2 = bytes .size 28 ; @newtype
; no longer in text/utf8
asset_name_v2 = bytes .size (0..64) ; @newtype

files_details = 
  {
    name : string64,
    mediaType : string64,
    src : chunkable_string
  }


chunkable_string =
    string64      ; @name single
    /
    [* string64]  ; @name chunked

metadata_details = 
  {
    name : string64,
    image : chunkable_string, 
    ? mediaType : string64,
    ? description : chunkable_string,
    ? files : [* files_details]
  }

label_metadata_v1 = { * policy_id_v1 => { * asset_name_v1 => metadata_details } }
data = { * policy_id_v2 => { * asset_name_v2 => metadata_details } }
label_metadata_v2 = { data: data, version: 2 } ; version 2

label_metadata = label_metadata_v1 / label_metadata_v2

CIP25Metadata = { 721 : label_metadata }
