[package]
name = "cml-multi-era"
version = "6.0.1"
edition = "2018"
authors = ["dcSpark"]
license = "MIT"
description = "Multiplatform SDK for era-agnostic Cardano blockchain parsing"
documentation = "https://github.com/dcSpark/cardano-multiplatform-lib/docs"
repository = "https://github.com/dcSpark/cardano-multiplatform-lib"
readme = "../../README.md"
keywords = ["cardano"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
used_from_wasm = ["wasm-bindgen"]

[dependencies]
cml-core = { path = "../../core/rust", version = "6.0.1" }
cml-crypto = { path = "../../crypto/rust", version = "6.0.1" }
cml-chain = { path = "../../chain/rust", version = "6.0.1" }
cbor_event.workspace = true
linked-hash-map.workspace = true
derivative.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true

# only for declaring hash types
bech32 = "0.7.2"
hex.workspace = true

# non-wasm
noop_proc_macro = { version = "0.3.0" }

# wasm
wasm-bindgen = { version = "0.2.87", optional = true }