vkey = _CDDL_CODEGEN_RAW_BYTES_TYPE_
VRF_vkey = _CDDL_CODEGEN_RAW_BYTES_TYPE_
natural = _CDDL_CODEGEN_RAW_BYTES_TYPE_
KES_vkey = _CDDL_CODEGEN_RAW_BYTES_TYPE_
ed25519_signature = _CDDL_CODEGEN_RAW_BYTES_TYPE_
ed25519_key_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_
genesis_delegate_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_
genesis_hash           = _CDDL_CODEGEN_RAW_BYTES_TYPE_
VRF_key_hash           = _CDDL_CODEGEN_RAW_BYTES_TYPE_
auxiliary_data_hash   = _CDDL_CODEGEN_RAW_BYTES_TYPE_
pool_metadata_hash    = _CDDL_CODEGEN_RAW_BYTES_TYPE_
script_hash            = _CDDL_CODEGEN_RAW_BYTES_TYPE_
datum_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_
block_body_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_
block_header_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_
transaction_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_
script_data_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_
anchor_doc_hash = _CDDL_CODEGEN_RAW_BYTES_TYPE_
