[package]
name = "cml-core-wasm"
version = "6.0.1"
edition = "2018"
keywords = ["cardano"]
license = "MIT"
description = "Multiplatform WASM SDK for core Cardano blockchain functionality"
documentation = "https://github.com/dcSpark/cardano-multiplatform-lib/docs"
repository = "https://github.com/dcSpark/cardano-multiplatform-lib"
readme = "../../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cml-core = { path = "../rust", version = "6.0.1" }
cbor_event.workspace = true
hex.workspace = true
wasm-bindgen.workspace = true
linked-hash-map.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
