stake_credential = _CDDL_CODEGEN_EXTERN_TYPE_
; also port, ipv4, single_host_addr, etc but these are only used by relay
relay = _CDDL_CODEGEN_EXTERN_TYPE_
pool_metadata = _CDDL_CODEGEN_EXTERN_TYPE_
single_host_addr = _CDDL_CODEGEN_EXTERN_TYPE_

; THESE CANNOT BE EXTERN SINCE THEY ARE PLAIN GROUPS SO DELETE THEM AFTER

stake_deregistration = (tag: 1, stake_credential)
stake_delegation = (
    tag: 2,
    stake_credential,
    ed25519_key_hash ; @name pool
)
pool_retirement = (
    tag: 4,
    ed25519_key_hash, ; @name pool
    epoch
)