stake_credential = _CDDL_CODEGEN_EXTERN_TYPE_
; also port, ipv4, single_host_addr, etc but these are only used by relay
relay = _CDDL_CODEGEN_EXTERN_TYPE_
pool_metadata = _CDDL_CODEGEN_EXTERN_TYPE_

; THESE CANNOT BE EXTERN SINCE THEY ARE PLAIN GROUPS SO DELETE THEM AFTER


stake_registration = (tag: 0, stake_credential)
stake_deregistration = (tag: 1, stake_credential)
stake_delegation = (
    tag: 2,
    stake_credential,
    ed25519_key_hash ; @name pool
)
pool_registration = (tag: 3, pool_params)
pool_retirement = (
    tag: 4,
    ed25519_key_hash, ; @name pool
    epoch
)

pool_params = ( operator:       ed25519_key_hash
              , vrf_keyhash:    VRF_key_hash
              , pledge:         coin
              , cost:           coin
              , margin:         unit_interval
              , reward_account: reward_account
              , pool_owners:    [* ed25519_key_hash]
              , relays:         [* relay]
              , pool_metadata:  pool_metadata / null
              )