transaction_input = _CDDL_CODEGEN_EXTERN_TYPE_
transaction_index = uint .size 2
transaction_metadatum_label = uint
transaction_metadatum = _CDDL_CODEGEN_EXTERN_TYPE_
transaction_body = _CDDL_CODEGEN_EXTERN_TYPE_
required_signers = [* ed25519_key_hash]
native_script = _CDDL_CODEGEN_EXTERN_TYPE_
alonzo_format_tx_out = _CDDL_CODEGEN_EXTERN_TYPE_
datum_option = _CDDL_CODEGEN_EXTERN_TYPE_