name: PR Checks

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.1'
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: prepare-rust
        run: |
          rustup install stable
          rustup target add wasm32-unknown-unknown --toolchain stable
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: install
        run: |
          npm install
      - name: rust:test
        run: |
          npm run rust:test
      - name: rust:build-nodejs
        run: |
          npm run rust:build-nodejs
      - name: rust:build-browser
        run: |
          npm run rust:build-browser
      - name: cargo-fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: cargo-clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-features --all-targets -- --deny "clippy::all"
      - name: all:test
        run: cargo test
      - name: cml:install
        working-directory: cml/wasm
        run: npm install
      - name: cml:rust:build-nodejs
        working-directory: cml/wasm
        run: npm run rust:build-nodejs
      - name: cml:rust:build-browser
        working-directory: cml/wasm
        run: npm run rust:build-browser
      - name: multi-era:install
        working-directory: multi-era/wasm
        run: npm install
      - name: multi-era:rust:build-nodejs
        working-directory: multi-era/wasm
        run: npm run rust:build-nodejs
      - name: multi-era:rust:build-browser
        working-directory: multi-era/wasm
        run: npm run rust:build-browser
